"""empty message

Revision ID: ae266c063be8
Revises: 7fb0bbb73429
Create Date: 2021-03-06 17:48:37.379462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae266c063be8'
down_revision = '7fb0bbb73429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('comments', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created', sa.DATETIME(), nullable=False))
    op.drop_column('comments', 'date')
    # ### end Alembic commands ###
